name: "Changelog"
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

env:
  BASE_BRANCH: main
  python-version: "3.13"

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Fetch all history
          fetch-depth: '0'

      - name: Setup uv
        uses: plone/meta/.github/actions/setup_uv@2.x
        with:
          python-version: ${{ env.python-version }}
          working-directory: '.'

      - name: Check for presence of a Change Log fragment (only pull requests)
        if: github.event_name == 'pull_request'
        run: |
          # Fetch the pull request' base branch so towncrier will be able to
          # compare the current branch with the base branch.
          # Source: https://github.com/actions/checkout/#fetch-all-branches.
          git fetch --no-tags origin ${BASE_BRANCH}
          uvx towncrier check  --compare-with origin/${{ env.BASE_BRANCH }} --config backend/pyproject.toml --dir backend/
